[package]
name = "gravity_set"
version = "0.0.0"
authors = ["Fred Mitchell <fred.mitchell@gmx.de>"]

[dependencies]
serde = "1.0.2"
serde_json = "1.0.1"
serde_derive = "1.0.2"
ndarray = "0.9.1"

[lib]
name = "gravityset"
crate-type = ["dylib"]
